services:
    ##########
    # Python #
    ##########
    python-ubuntu-focal-amd64:
        build:
            context: .
            dockerfile: ./docker/python.Dockerfile
            args:
                - BUILD_IMAGE=ubuntu:focal
                - PLATFORM=linux/amd64
                - UID=1000
                - GID=1000
                - TZ=America/Toronto
                - PYTHON_VERSION=3.12.13
                - GCC_VERSION=16.1.0
                - GDB_VERSION=17.1
                - VALGRIND_VERSION=3.27.0
                - DOXYGEN_VERSION=1.17.0
                - CMAKE_VERSION=3.31.12
                - LLVM_VERSION=22
        platform: linux/amd64
        volumes:
            - ./out:/out
        command: ["/bin/sh", "-c", "cp -a /home/factoryengine/out/. /out"]

    python-ubuntu-focal-arm64:
        build:
            context: .
            dockerfile: ./docker/python.Dockerfile
            args:
                - BUILD_IMAGE=ubuntu:focal
                - PLATFORM=linux/arm64
                - UID=1000
                - GID=1000
                - TZ=America/Toronto
                - PYTHON_VERSION=3.12.13
                - GCC_VERSION=16.1.0
                - GDB_VERSION=17.1
                - VALGRIND_VERSION=3.27.0
                - DOXYGEN_VERSION=1.17.0
                - CMAKE_VERSION=3.31.12
                - LLVM_VERSION=22
        platform: linux/arm64
        volumes:
            - ./out:/out
        command: ["/bin/sh", "-c", "cp -a /home/factoryengine/out/. /out"]

    python-ubuntu-jammy-amd64:
        build:
            context: .
            dockerfile: ./docker/python.Dockerfile
            args:
                - BUILD_IMAGE=ubuntu:jammy
                - PLATFORM=linux/amd64
                - UID=1000
                - GID=1000
                - TZ=America/Toronto
                - PYTHON_VERSION=3.12.13
                - GCC_VERSION=16.1.0
                - GDB_VERSION=17.1
                - VALGRIND_VERSION=3.27.0
                - DOXYGEN_VERSION=1.17.0
                - CMAKE_VERSION=3.31.12
                - LLVM_VERSION=22
        platform: linux/amd64
        volumes:
            - ./out:/out
        command: ["/bin/sh", "-c", "cp -a /home/factoryengine/out/. /out"]

    python-ubuntu-jammy-arm64:
        build:
            context: .
            dockerfile: ./docker/python.Dockerfile
            args:
                - BUILD_IMAGE=ubuntu:jammy
                - PLATFORM=linux/arm64
                - UID=1000
                - GID=1000
                - TZ=America/Toronto
                - PYTHON_VERSION=3.12.13
                - GCC_VERSION=16.1.0
                - GDB_VERSION=17.1
                - VALGRIND_VERSION=3.27.0
                - DOXYGEN_VERSION=1.17.0
                - CMAKE_VERSION=3.31.12
                - LLVM_VERSION=22
        platform: linux/arm64
        volumes:
            - ./out:/out
        command: ["/bin/sh", "-c", "cp -a /home/factoryengine/out/. /out"]

    python-ubuntu-noble-amd64:
        build:
            context: .
            dockerfile: ./docker/python.Dockerfile
            args:
                - BUILD_IMAGE=ubuntu:noble
                - PLATFORM=linux/amd64
                - UID=1000
                - GID=1000
                - TZ=America/Toronto
                - PYTHON_VERSION=3.12.13
                - GCC_VERSION=16.1.0
                - GDB_VERSION=17.1
                - VALGRIND_VERSION=3.27.0
                - DOXYGEN_VERSION=1.17.0
                - CMAKE_VERSION=3.31.12
                - LLVM_VERSION=22
        platform: linux/amd64
        volumes:
            - ./out:/out
        command: ["/bin/sh", "-c", "cp -a /home/factoryengine/out/. /out"]

    python-ubuntu-noble-arm64:
        build:
            context: .
            dockerfile: ./docker/python.Dockerfile
            args:
                - BUILD_IMAGE=ubuntu:noble
                - PLATFORM=linux/arm64
                - UID=1000
                - GID=1000
                - TZ=America/Toronto
                - PYTHON_VERSION=3.12.13
                - GCC_VERSION=16.1.0
                - GDB_VERSION=17.1
                - VALGRIND_VERSION=3.27.0
                - DOXYGEN_VERSION=1.17.0
                - CMAKE_VERSION=3.31.12
                - LLVM_VERSION=22
        platform: linux/arm64
        volumes:
            - ./out:/out
        command: ["/bin/sh", "-c", "cp -a /home/factoryengine/out/. /out"]

    python-ubuntu-resolute-amd64:
        build:
            context: .
            dockerfile: ./docker/python.Dockerfile
            args:
                - BUILD_IMAGE=ubuntu:resolute
                - PLATFORM=linux/amd64
                - UID=1000
                - GID=1000
                - TZ=America/Toronto
                - PYTHON_VERSION=3.12.13
                - GCC_VERSION=16.1.0
                - GDB_VERSION=17.1
                - VALGRIND_VERSION=3.27.0
                - DOXYGEN_VERSION=1.17.0
                - CMAKE_VERSION=3.31.12
                - LLVM_VERSION=22
        platform: linux/amd64
        volumes:
            - ./out:/out
        command: ["/bin/sh", "-c", "cp -a /home/factoryengine/out/. /out"]

    python-ubuntu-resolute-arm64:
        build:
            context: .
            dockerfile: ./docker/python.Dockerfile
            args:
                - BUILD_IMAGE=ubuntu:resolute
                - PLATFORM=linux/arm64
                - UID=1000
                - GID=1000
                - TZ=America/Toronto
                - PYTHON_VERSION=3.12.13
                - GCC_VERSION=16.1.0
                - GDB_VERSION=17.1
                - VALGRIND_VERSION=3.27.0
                - DOXYGEN_VERSION=1.17.0
                - CMAKE_VERSION=3.31.12
                - LLVM_VERSION=22
        platform: linux/arm64
        volumes:
            - ./out:/out
        command: ["/bin/sh", "-c", "cp -a /home/factoryengine/out/. /out"]

    python-debian-bullseye-amd64:
        build:
            context: .
            dockerfile: ./docker/python.Dockerfile
            args:
                - BUILD_IMAGE=debian:bullseye
                - PLATFORM=linux/amd64
                - UID=1000
                - GID=1000
                - TZ=America/Toronto
                - PYTHON_VERSION=3.12.13
                - GCC_VERSION=16.1.0
                - GDB_VERSION=17.1
                - VALGRIND_VERSION=3.27.0
                - DOXYGEN_VERSION=1.17.0
                - CMAKE_VERSION=3.31.12
                - LLVM_VERSION=22
        platform: linux/amd64
        volumes:
            - ./out:/out
        command: ["/bin/sh", "-c", "cp -a /home/factoryengine/out/. /out"]

    python-debian-bullseye-arm64:
        build:
            context: .
            dockerfile: ./docker/python.Dockerfile
            args:
                - BUILD_IMAGE=debian:bullseye
                - PLATFORM=linux/arm64
                - UID=1000
                - GID=1000
                - TZ=America/Toronto
                - PYTHON_VERSION=3.12.13
                - GCC_VERSION=16.1.0
                - GDB_VERSION=17.1
                - VALGRIND_VERSION=3.27.0
                - DOXYGEN_VERSION=1.17.0
                - CMAKE_VERSION=3.31.12
                - LLVM_VERSION=22
        platform: linux/arm64
        volumes:
            - ./out:/out
        command: ["/bin/sh", "-c", "cp -a /home/factoryengine/out/. /out"]

    python-debian-bookworm-amd64:
        build:
            context: .
            dockerfile: ./docker/python.Dockerfile
            args:
                - BUILD_IMAGE=debian:bookworm
                - PLATFORM=linux/amd64
                - UID=1000
                - GID=1000
                - TZ=America/Toronto
                - PYTHON_VERSION=3.12.13
                - GCC_VERSION=16.1.0
                - GDB_VERSION=17.1
                - VALGRIND_VERSION=3.27.0
                - DOXYGEN_VERSION=1.17.0
                - CMAKE_VERSION=3.31.12
                - LLVM_VERSION=22
        platform: linux/amd64
        volumes:
            - ./out:/out
        command: ["/bin/sh", "-c", "cp -a /home/factoryengine/out/. /out"]

    python-debian-bookworm-arm64:
        build:
            context: .
            dockerfile: ./docker/python.Dockerfile
            args:
                - BUILD_IMAGE=debian:bookworm
                - PLATFORM=linux/arm64
                - UID=1000
                - GID=1000
                - TZ=America/Toronto
                - PYTHON_VERSION=3.12.13
                - GCC_VERSION=16.1.0
                - GDB_VERSION=17.1
                - VALGRIND_VERSION=3.27.0
                - DOXYGEN_VERSION=1.17.0
                - CMAKE_VERSION=3.31.12
                - LLVM_VERSION=22
        platform: linux/arm64
        volumes:
            - ./out:/out
        command: ["/bin/sh", "-c", "cp -a /home/factoryengine/out/. /out"]

    python-debian-trixie-amd64:
        build:
            context: .
            dockerfile: ./docker/python.Dockerfile
            args:
                - BUILD_IMAGE=debian:trixie
                - PLATFORM=linux/amd64
                - UID=1000
                - GID=1000
                - TZ=America/Toronto
                - PYTHON_VERSION=3.12.13
                - GCC_VERSION=16.1.0
                - GDB_VERSION=17.1
                - VALGRIND_VERSION=3.27.0
                - DOXYGEN_VERSION=1.17.0
                - CMAKE_VERSION=3.31.12
                - LLVM_VERSION=22
        platform: linux/amd64
        volumes:
            - ./out:/out
        command: ["/bin/sh", "-c", "cp -a /home/factoryengine/out/. /out"]

    python-debian-trixie-arm64:
        build:
            context: .
            dockerfile: ./docker/python.Dockerfile
            args:
                - BUILD_IMAGE=debian:trixie
                - PLATFORM=linux/arm64
                - UID=1000
                - GID=1000
                - TZ=America/Toronto
                - PYTHON_VERSION=3.12.13
                - GCC_VERSION=16.1.0
                - GDB_VERSION=17.1
                - VALGRIND_VERSION=3.27.0
                - DOXYGEN_VERSION=1.17.0
                - CMAKE_VERSION=3.31.12
                - LLVM_VERSION=22
        platform: linux/arm64
        volumes:
            - ./out:/out
        command: ["/bin/sh", "-c", "cp -a /home/factoryengine/out/. /out"]

    python-alpine-3.23-amd64:
        build:
            context: .
            dockerfile: ./docker/python.Dockerfile
            args:
                - BUILD_IMAGE=alpine:3.23
                - PLATFORM=linux/amd64
                - UID=1000
                - GID=1000
                - TZ=America/Toronto
                - PYTHON_VERSION=3.12.13
                - GCC_VERSION=16.1.0
                - GDB_VERSION=17.1
                - VALGRIND_VERSION=3.27.0
                - DOXYGEN_VERSION=1.17.0
                - CMAKE_VERSION=3.31.12
                - LLVM_VERSION=22
        platform: linux/amd64
        volumes:
            - ./out:/out
        command: ["/bin/sh", "-c", "cp -a /home/factoryengine/out/. /out"]

    python-alpine-3.23-arm64:
        build:
            context: .
            dockerfile: ./docker/python.Dockerfile
            args:
                - BUILD_IMAGE=alpine:3.23
                - PLATFORM=linux/arm64
                - UID=1000
                - GID=1000
                - TZ=America/Toronto
                - PYTHON_VERSION=3.12.13
                - GCC_VERSION=16.1.0
                - GDB_VERSION=17.1
                - VALGRIND_VERSION=3.27.0
                - DOXYGEN_VERSION=1.17.0
                - CMAKE_VERSION=3.31.12
                - LLVM_VERSION=22
        platform: linux/arm64
        volumes:
            - ./out:/out
        command: ["/bin/sh", "-c", "cp -a /home/factoryengine/out/. /out"]

    #######
    # CPP #
    #######
    cpp-ubuntu-focal-amd64:
        build:
            context: .
            dockerfile: ./docker/cpp.Dockerfile
            args:
                - BUILD_IMAGE=ubuntu:focal
                - PLATFORM=linux/amd64
                - UID=1000
                - GID=1000
                - TZ=America/Toronto
                - PYTHON_VERSION=3.12.13
                - GCC_VERSION=16.1.0
                - GDB_VERSION=17.1
                - VALGRIND_VERSION=3.27.0
                - DOXYGEN_VERSION=1.17.0
                - CMAKE_VERSION=3.31.12
                - LLVM_VERSION=22
        platform: linux/amd64
        volumes:
            - ./out:/out
        command: ["/bin/sh", "-c", "cp -a /home/factoryengine/out/. /out"]

    cpp-ubuntu-focal-arm64:
        build:
            context: .
            dockerfile: ./docker/cpp.Dockerfile
            args:
                - BUILD_IMAGE=ubuntu:focal
                - PLATFORM=linux/arm64
                - UID=1000
                - GID=1000
                - TZ=America/Toronto
                - PYTHON_VERSION=3.12.13
                - GCC_VERSION=16.1.0
                - GDB_VERSION=17.1
                - VALGRIND_VERSION=3.27.0
                - DOXYGEN_VERSION=1.17.0
                - CMAKE_VERSION=3.31.12
                - LLVM_VERSION=22
        platform: linux/arm64
        volumes:
            - ./out:/out
        command: ["/bin/sh", "-c", "cp -a /home/factoryengine/out/. /out"]

    cpp-ubuntu-jammy-amd64:
        build:
            context: .
            dockerfile: ./docker/cpp.Dockerfile
            args:
                - BUILD_IMAGE=ubuntu:jammy
                - PLATFORM=linux/amd64
                - UID=1000
                - GID=1000
                - TZ=America/Toronto
                - PYTHON_VERSION=3.12.13
                - GCC_VERSION=16.1.0
                - GDB_VERSION=17.1
                - VALGRIND_VERSION=3.27.0
                - DOXYGEN_VERSION=1.17.0
                - CMAKE_VERSION=3.31.12
                - LLVM_VERSION=22
        platform: linux/amd64
        volumes:
            - ./out:/out
        command: ["/bin/sh", "-c", "cp -a /home/factoryengine/out/. /out"]

    cpp-ubuntu-jammy-arm64:
        build:
            context: .
            dockerfile: ./docker/cpp.Dockerfile
            args:
                - BUILD_IMAGE=ubuntu:jammy
                - PLATFORM=linux/arm64
                - UID=1000
                - GID=1000
                - TZ=America/Toronto
                - PYTHON_VERSION=3.12.13
                - GCC_VERSION=16.1.0
                - GDB_VERSION=17.1
                - VALGRIND_VERSION=3.27.0
                - DOXYGEN_VERSION=1.17.0
                - CMAKE_VERSION=3.31.12
                - LLVM_VERSION=22
        platform: linux/arm64
        volumes:
            - ./out:/out
        command: ["/bin/sh", "-c", "cp -a /home/factoryengine/out/. /out"]

    cpp-ubuntu-noble-amd64:
        build:
            context: .
            dockerfile: ./docker/cpp.Dockerfile
            args:
                - BUILD_IMAGE=ubuntu:noble
                - PLATFORM=linux/amd64
                - UID=1000
                - GID=1000
                - TZ=America/Toronto
                - PYTHON_VERSION=3.12.13
                - GCC_VERSION=16.1.0
                - GDB_VERSION=17.1
                - VALGRIND_VERSION=3.27.0
                - DOXYGEN_VERSION=1.17.0
                - CMAKE_VERSION=3.31.12
                - LLVM_VERSION=22
        platform: linux/amd64
        volumes:
            - ./out:/out
        command: ["/bin/sh", "-c", "cp -a /home/factoryengine/out/. /out"]

    cpp-ubuntu-noble-arm64:
        build:
            context: .
            dockerfile: ./docker/cpp.Dockerfile
            args:
                - BUILD_IMAGE=ubuntu:noble
                - PLATFORM=linux/arm64
                - UID=1000
                - GID=1000
                - TZ=America/Toronto
                - PYTHON_VERSION=3.12.13
                - GCC_VERSION=16.1.0
                - GDB_VERSION=17.1
                - VALGRIND_VERSION=3.27.0
                - DOXYGEN_VERSION=1.17.0
                - CMAKE_VERSION=3.31.12
                - LLVM_VERSION=22
        platform: linux/arm64
        volumes:
            - ./out:/out
        command: ["/bin/sh", "-c", "cp -a /home/factoryengine/out/. /out"]

    cpp-ubuntu-resolute-amd64:
        build:
            context: .
            dockerfile: ./docker/cpp.Dockerfile
            args:
                - BUILD_IMAGE=ubuntu:resolute
                - PLATFORM=linux/amd64
                - UID=1000
                - GID=1000
                - TZ=America/Toronto
                - PYTHON_VERSION=3.12.13
                - GCC_VERSION=16.1.0
                - GDB_VERSION=17.1
                - VALGRIND_VERSION=3.27.0
                - DOXYGEN_VERSION=1.17.0
                - CMAKE_VERSION=3.31.12
                - LLVM_VERSION=22
        platform: linux/amd64
        volumes:
            - ./out:/out
        command: ["/bin/sh", "-c", "cp -a /home/factoryengine/out/. /out"]

    cpp-ubuntu-resolute-arm64:
        build:
            context: .
            dockerfile: ./docker/cpp.Dockerfile
            args:
                - BUILD_IMAGE=ubuntu:resolute
                - PLATFORM=linux/arm64
                - UID=1000
                - GID=1000
                - TZ=America/Toronto
                - PYTHON_VERSION=3.12.13
                - GCC_VERSION=16.1.0
                - GDB_VERSION=17.1
                - VALGRIND_VERSION=3.27.0
                - DOXYGEN_VERSION=1.17.0
                - CMAKE_VERSION=3.31.12
                - LLVM_VERSION=22
        platform: linux/arm64
        volumes:
            - ./out:/out
        command: ["/bin/sh", "-c", "cp -a /home/factoryengine/out/. /out"]

    cpp-debian-bullseye-amd64:
        build:
            context: .
            dockerfile: ./docker/cpp.Dockerfile
            args:
                - BUILD_IMAGE=debian:bullseye
                - PLATFORM=linux/amd64
                - UID=1000
                - GID=1000
                - TZ=America/Toronto
                - PYTHON_VERSION=3.12.13
                - GCC_VERSION=16.1.0
                - GDB_VERSION=17.1
                - VALGRIND_VERSION=3.27.0
                - DOXYGEN_VERSION=1.17.0
                - CMAKE_VERSION=3.31.12
                - LLVM_VERSION=22
        platform: linux/amd64
        volumes:
            - ./out:/out
        command: ["/bin/sh", "-c", "cp -a /home/factoryengine/out/. /out"]

    cpp-debian-bullseye-arm64:
        build:
            context: .
            dockerfile: ./docker/cpp.Dockerfile
            args:
                - BUILD_IMAGE=debian:bullseye
                - PLATFORM=linux/arm64
                - UID=1000
                - GID=1000
                - TZ=America/Toronto
                - PYTHON_VERSION=3.12.13
                - GCC_VERSION=16.1.0
                - GDB_VERSION=17.1
                - VALGRIND_VERSION=3.27.0
                - DOXYGEN_VERSION=1.17.0
                - CMAKE_VERSION=3.31.12
                - LLVM_VERSION=22
        platform: linux/arm64
        volumes:
            - ./out:/out
        command: ["/bin/sh", "-c", "cp -a /home/factoryengine/out/. /out"]

    cpp-debian-bookworm-amd64:
        build:
            context: .
            dockerfile: ./docker/cpp.Dockerfile
            args:
                - BUILD_IMAGE=debian:bookworm
                - PLATFORM=linux/amd64
                - UID=1000
                - GID=1000
                - TZ=America/Toronto
                - PYTHON_VERSION=3.12.13
                - GCC_VERSION=16.1.0
                - GDB_VERSION=17.1
                - VALGRIND_VERSION=3.27.0
                - DOXYGEN_VERSION=1.17.0
                - CMAKE_VERSION=3.31.12
                - LLVM_VERSION=22
        platform: linux/amd64
        volumes:
            - ./out:/out
        command: ["/bin/sh", "-c", "cp -a /home/factoryengine/out/. /out"]

    cpp-debian-bookworm-arm64:
        build:
            context: .
            dockerfile: ./docker/cpp.Dockerfile
            args:
                - BUILD_IMAGE=debian:bookworm
                - PLATFORM=linux/arm64
                - UID=1000
                - GID=1000
                - TZ=America/Toronto
                - PYTHON_VERSION=3.12.13
                - GCC_VERSION=16.1.0
                - GDB_VERSION=17.1
                - VALGRIND_VERSION=3.27.0
                - DOXYGEN_VERSION=1.17.0
                - CMAKE_VERSION=3.31.12
                - LLVM_VERSION=22
        platform: linux/arm64
        volumes:
            - ./out:/out
        command: ["/bin/sh", "-c", "cp -a /home/factoryengine/out/. /out"]

    cpp-debian-trixie-amd64:
        build:
            context: .
            dockerfile: ./docker/cpp.Dockerfile
            args:
                - BUILD_IMAGE=debian:trixie
                - PLATFORM=linux/amd64
                - UID=1000
                - GID=1000
                - TZ=America/Toronto
                - PYTHON_VERSION=3.12.13
                - GCC_VERSION=16.1.0
                - GDB_VERSION=17.1
                - VALGRIND_VERSION=3.27.0
                - DOXYGEN_VERSION=1.17.0
                - CMAKE_VERSION=3.31.12
                - LLVM_VERSION=22
        platform: linux/amd64
        volumes:
            - ./out:/out
        command: ["/bin/sh", "-c", "cp -a /home/factoryengine/out/. /out"]

    cpp-debian-trixie-arm64:
        build:
            context: .
            dockerfile: ./docker/cpp.Dockerfile
            args:
                - BUILD_IMAGE=debian:trixie
                - PLATFORM=linux/arm64
                - UID=1000
                - GID=1000
                - TZ=America/Toronto
                - PYTHON_VERSION=3.12.13
                - GCC_VERSION=16.1.0
                - GDB_VERSION=17.1
                - VALGRIND_VERSION=3.27.0
                - DOXYGEN_VERSION=1.17.0
                - CMAKE_VERSION=3.31.12
                - LLVM_VERSION=22
        platform: linux/arm64
        volumes:
            - ./out:/out
        command: ["/bin/sh", "-c", "cp -a /home/factoryengine/out/. /out"]

    ############
    # Valgrind #
    ############
    valgrind-ubuntu-focal-amd64:
        build:
            context: .
            dockerfile: ./docker/valgrind.Dockerfile
            args:
                - BUILD_IMAGE=ubuntu:focal
                - PLATFORM=linux/amd64
                - UID=1000
                - GID=1000
                - TZ=America/Toronto
                - PYTHON_VERSION=3.12.13
                - GCC_VERSION=16.1.0
                - GDB_VERSION=17.1
                - VALGRIND_VERSION=3.27.0
                - DOXYGEN_VERSION=1.17.0
                - CMAKE_VERSION=3.31.12
                - LLVM_VERSION=22
        platform: linux/amd64
        volumes:
            - ./out:/out
        command: ["/bin/sh", "-c", "cp -a /home/factoryengine/out/. /out"]

    valgrind-ubuntu-focal-arm64:
        build:
            context: .
            dockerfile: ./docker/valgrind.Dockerfile
            args:
                - BUILD_IMAGE=ubuntu:focal
                - PLATFORM=linux/arm64
                - UID=1000
                - GID=1000
                - TZ=America/Toronto
                - PYTHON_VERSION=3.12.13
                - GCC_VERSION=16.1.0
                - GDB_VERSION=17.1
                - VALGRIND_VERSION=3.27.0
                - DOXYGEN_VERSION=1.17.0
                - CMAKE_VERSION=3.31.12
                - LLVM_VERSION=22
        platform: linux/arm64
        volumes:
            - ./out:/out
        command: ["/bin/sh", "-c", "cp -a /home/factoryengine/out/. /out"]

    valgrind-ubuntu-jammy-amd64:
        build:
            context: .
            dockerfile: ./docker/valgrind.Dockerfile
            args:
                - BUILD_IMAGE=ubuntu:jammy
                - PLATFORM=linux/amd64
                - UID=1000
                - GID=1000
                - TZ=America/Toronto
                - PYTHON_VERSION=3.12.13
                - GCC_VERSION=16.1.0
                - GDB_VERSION=17.1
                - VALGRIND_VERSION=3.27.0
                - DOXYGEN_VERSION=1.17.0
                - CMAKE_VERSION=3.31.12
                - LLVM_VERSION=22
        platform: linux/amd64
        volumes:
            - ./out:/out
        command: ["/bin/sh", "-c", "cp -a /home/factoryengine/out/. /out"]

    valgrind-ubuntu-jammy-arm64:
        build:
            context: .
            dockerfile: ./docker/valgrind.Dockerfile
            args:
                - BUILD_IMAGE=ubuntu:jammy
                - PLATFORM=linux/arm64
                - UID=1000
                - GID=1000
                - TZ=America/Toronto
                - PYTHON_VERSION=3.12.13
                - GCC_VERSION=16.1.0
                - GDB_VERSION=17.1
                - VALGRIND_VERSION=3.27.0
                - DOXYGEN_VERSION=1.17.0
                - CMAKE_VERSION=3.31.12
                - LLVM_VERSION=22
        platform: linux/arm64
        volumes:
            - ./out:/out
        command: ["/bin/sh", "-c", "cp -a /home/factoryengine/out/. /out"]

    valgrind-ubuntu-noble-amd64:
        build:
            context: .
            dockerfile: ./docker/valgrind.Dockerfile
            args:
                - BUILD_IMAGE=ubuntu:noble
                - PLATFORM=linux/amd64
                - UID=1000
                - GID=1000
                - TZ=America/Toronto
                - PYTHON_VERSION=3.12.13
                - GCC_VERSION=16.1.0
                - GDB_VERSION=17.1
                - VALGRIND_VERSION=3.27.0
                - DOXYGEN_VERSION=1.17.0
                - CMAKE_VERSION=3.31.12
                - LLVM_VERSION=22
        platform: linux/amd64
        volumes:
            - ./out:/out
        command: ["/bin/sh", "-c", "cp -a /home/factoryengine/out/. /out"]

    valgrind-ubuntu-noble-arm64:
        build:
            context: .
            dockerfile: ./docker/valgrind.Dockerfile
            args:
                - BUILD_IMAGE=ubuntu:noble
                - PLATFORM=linux/arm64
                - UID=1000
                - GID=1000
                - TZ=America/Toronto
                - PYTHON_VERSION=3.12.13
                - GCC_VERSION=16.1.0
                - GDB_VERSION=17.1
                - VALGRIND_VERSION=3.27.0
                - DOXYGEN_VERSION=1.17.0
                - CMAKE_VERSION=3.31.12
                - LLVM_VERSION=22
        platform: linux/arm64
        volumes:
            - ./out:/out
        command: ["/bin/sh", "-c", "cp -a /home/factoryengine/out/. /out"]

    valgrind-ubuntu-resolute-amd64:
        build:
            context: .
            dockerfile: ./docker/valgrind.Dockerfile
            args:
                - BUILD_IMAGE=ubuntu:resolute
                - PLATFORM=linux/amd64
                - UID=1000
                - GID=1000
                - TZ=America/Toronto
                - PYTHON_VERSION=3.12.13
                - GCC_VERSION=16.1.0
                - GDB_VERSION=17.1
                - VALGRIND_VERSION=3.27.0
                - DOXYGEN_VERSION=1.17.0
                - CMAKE_VERSION=3.31.12
                - LLVM_VERSION=22
        platform: linux/amd64
        volumes:
            - ./out:/out
        command: ["/bin/sh", "-c", "cp -a /home/factoryengine/out/. /out"]

    valgrind-ubuntu-resolute-arm64:
        build:
            context: .
            dockerfile: ./docker/valgrind.Dockerfile
            args:
                - BUILD_IMAGE=ubuntu:resolute
                - PLATFORM=linux/arm64
                - UID=1000
                - GID=1000
                - TZ=America/Toronto
                - PYTHON_VERSION=3.12.13
                - GCC_VERSION=16.1.0
                - GDB_VERSION=17.1
                - VALGRIND_VERSION=3.27.0
                - DOXYGEN_VERSION=1.17.0
                - CMAKE_VERSION=3.31.12
                - LLVM_VERSION=22
        platform: linux/arm64
        volumes:
            - ./out:/out
        command: ["/bin/sh", "-c", "cp -a /home/factoryengine/out/. /out"]

    valgrind-debian-bullseye-amd64:
        build:
            context: .
            dockerfile: ./docker/valgrind.Dockerfile
            args:
                - BUILD_IMAGE=debian:bullseye
                - PLATFORM=linux/amd64
                - UID=1000
                - GID=1000
                - TZ=America/Toronto
                - PYTHON_VERSION=3.12.13
                - GCC_VERSION=16.1.0
                - GDB_VERSION=17.1
                - VALGRIND_VERSION=3.27.0
                - DOXYGEN_VERSION=1.17.0
                - CMAKE_VERSION=3.31.12
                - LLVM_VERSION=22
        platform: linux/amd64
        volumes:
            - ./out:/out
        command: ["/bin/sh", "-c", "cp -a /home/factoryengine/out/. /out"]

    valgrind-debian-bullseye-arm64:
        build:
            context: .
            dockerfile: ./docker/valgrind.Dockerfile
            args:
                - BUILD_IMAGE=debian:bullseye
                - PLATFORM=linux/arm64
                - UID=1000
                - GID=1000
                - TZ=America/Toronto
                - PYTHON_VERSION=3.12.13
                - GCC_VERSION=16.1.0
                - GDB_VERSION=17.1
                - VALGRIND_VERSION=3.27.0
                - DOXYGEN_VERSION=1.17.0
                - CMAKE_VERSION=3.31.12
                - LLVM_VERSION=22
        platform: linux/arm64
        volumes:
            - ./out:/out
        command: ["/bin/sh", "-c", "cp -a /home/factoryengine/out/. /out"]

    valgrind-debian-bookworm-amd64:
        build:
            context: .
            dockerfile: ./docker/valgrind.Dockerfile
            args:
                - BUILD_IMAGE=debian:bookworm
                - PLATFORM=linux/amd64
                - UID=1000
                - GID=1000
                - TZ=America/Toronto
                - PYTHON_VERSION=3.12.13
                - GCC_VERSION=16.1.0
                - GDB_VERSION=17.1
                - VALGRIND_VERSION=3.27.0
                - DOXYGEN_VERSION=1.17.0
                - CMAKE_VERSION=3.31.12
                - LLVM_VERSION=22
        platform: linux/amd64
        volumes:
            - ./out:/out
        command: ["/bin/sh", "-c", "cp -a /home/factoryengine/out/. /out"]

    valgrind-debian-bookworm-arm64:
        build:
            context: .
            dockerfile: ./docker/valgrind.Dockerfile
            args:
                - BUILD_IMAGE=debian:bookworm
                - PLATFORM=linux/arm64
                - UID=1000
                - GID=1000
                - TZ=America/Toronto
                - PYTHON_VERSION=3.12.13
                - GCC_VERSION=16.1.0
                - GDB_VERSION=17.1
                - VALGRIND_VERSION=3.27.0
                - DOXYGEN_VERSION=1.17.0
                - CMAKE_VERSION=3.31.12
                - LLVM_VERSION=22
        platform: linux/arm64
        volumes:
            - ./out:/out
        command: ["/bin/sh", "-c", "cp -a /home/factoryengine/out/. /out"]

    valgrind-debian-trixie-amd64:
        build:
            context: .
            dockerfile: ./docker/valgrind.Dockerfile
            args:
                - BUILD_IMAGE=debian:trixie
                - PLATFORM=linux/amd64
                - UID=1000
                - GID=1000
                - TZ=America/Toronto
                - PYTHON_VERSION=3.12.13
                - GCC_VERSION=16.1.0
                - GDB_VERSION=17.1
                - VALGRIND_VERSION=3.27.0
                - DOXYGEN_VERSION=1.17.0
                - CMAKE_VERSION=3.31.12
                - LLVM_VERSION=22
        platform: linux/amd64
        volumes:
            - ./out:/out
        command: ["/bin/sh", "-c", "cp -a /home/factoryengine/out/. /out"]

    valgrind-debian-trixie-arm64:
        build:
            context: .
            dockerfile: ./docker/valgrind.Dockerfile
            args:
                - BUILD_IMAGE=debian:trixie
                - PLATFORM=linux/arm64
                - UID=1000
                - GID=1000
                - TZ=America/Toronto
                - PYTHON_VERSION=3.12.13
                - GCC_VERSION=16.1.0
                - GDB_VERSION=17.1
                - VALGRIND_VERSION=3.27.0
                - DOXYGEN_VERSION=1.17.0
                - CMAKE_VERSION=3.31.12
                - LLVM_VERSION=22
        platform: linux/arm64
        volumes:
            - ./out:/out
        command: ["/bin/sh", "-c", "cp -a /home/factoryengine/out/. /out"]

    ###########
    # Doxygen #
    ###########
    doxygen-ubuntu-focal-amd64:
        build:
            context: .
            dockerfile: ./docker/doxygen.Dockerfile
            args:
                - BUILD_IMAGE=ubuntu:focal
                - PLATFORM=linux/amd64
                - UID=1000
                - GID=1000
                - TZ=America/Toronto
                - PYTHON_VERSION=3.12.13
                - GCC_VERSION=16.1.0
                - GDB_VERSION=17.1
                - VALGRIND_VERSION=3.27.0
                - DOXYGEN_VERSION=1.17.0
                - CMAKE_VERSION=3.31.12
                - LLVM_VERSION=22
        platform: linux/amd64
        volumes:
            - ./out:/out
        command: ["/bin/sh", "-c", "cp -a /home/factoryengine/out/. /out"]

    doxygen-ubuntu-focal-arm64:
        build:
            context: .
            dockerfile: ./docker/doxygen.Dockerfile
            args:
                - BUILD_IMAGE=ubuntu:focal
                - PLATFORM=linux/arm64
                - UID=1000
                - GID=1000
                - TZ=America/Toronto
                - PYTHON_VERSION=3.12.13
                - GCC_VERSION=16.1.0
                - GDB_VERSION=17.1
                - VALGRIND_VERSION=3.27.0
                - DOXYGEN_VERSION=1.17.0
                - CMAKE_VERSION=3.31.12
                - LLVM_VERSION=22
        platform: linux/arm64
        volumes:
            - ./out:/out
        command: ["/bin/sh", "-c", "cp -a /home/factoryengine/out/. /out"]

    doxygen-ubuntu-jammy-amd64:
        build:
            context: .
            dockerfile: ./docker/doxygen.Dockerfile
            args:
                - BUILD_IMAGE=ubuntu:jammy
                - PLATFORM=linux/amd64
                - UID=1000
                - GID=1000
                - TZ=America/Toronto
                - PYTHON_VERSION=3.12.13
                - GCC_VERSION=16.1.0
                - GDB_VERSION=17.1
                - VALGRIND_VERSION=3.27.0
                - DOXYGEN_VERSION=1.17.0
                - CMAKE_VERSION=3.31.12
                - LLVM_VERSION=22
        platform: linux/amd64
        volumes:
            - ./out:/out
        command: ["/bin/sh", "-c", "cp -a /home/factoryengine/out/. /out"]

    doxygen-ubuntu-jammy-arm64:
        build:
            context: .
            dockerfile: ./docker/doxygen.Dockerfile
            args:
                - BUILD_IMAGE=ubuntu:jammy
                - PLATFORM=linux/arm64
                - UID=1000
                - GID=1000
                - TZ=America/Toronto
                - PYTHON_VERSION=3.12.13
                - GCC_VERSION=16.1.0
                - GDB_VERSION=17.1
                - VALGRIND_VERSION=3.27.0
                - DOXYGEN_VERSION=1.17.0
                - CMAKE_VERSION=3.31.12
                - LLVM_VERSION=22
        platform: linux/arm64
        volumes:
            - ./out:/out
        command: ["/bin/sh", "-c", "cp -a /home/factoryengine/out/. /out"]

    doxygen-ubuntu-noble-amd64:
        build:
            context: .
            dockerfile: ./docker/doxygen.Dockerfile
            args:
                - BUILD_IMAGE=ubuntu:noble
                - PLATFORM=linux/amd64
                - UID=1000
                - GID=1000
                - TZ=America/Toronto
                - PYTHON_VERSION=3.12.13
                - GCC_VERSION=16.1.0
                - GDB_VERSION=17.1
                - VALGRIND_VERSION=3.27.0
                - DOXYGEN_VERSION=1.17.0
                - CMAKE_VERSION=3.31.12
                - LLVM_VERSION=22
        platform: linux/amd64
        volumes:
            - ./out:/out
        command: ["/bin/sh", "-c", "cp -a /home/factoryengine/out/. /out"]

    doxygen-ubuntu-noble-arm64:
        build:
            context: .
            dockerfile: ./docker/doxygen.Dockerfile
            args:
                - BUILD_IMAGE=ubuntu:noble
                - PLATFORM=linux/arm64
                - UID=1000
                - GID=1000
                - TZ=America/Toronto
                - PYTHON_VERSION=3.12.13
                - GCC_VERSION=16.1.0
                - GDB_VERSION=17.1
                - VALGRIND_VERSION=3.27.0
                - DOXYGEN_VERSION=1.17.0
                - CMAKE_VERSION=3.31.12
                - LLVM_VERSION=22
        platform: linux/arm64
        volumes:
            - ./out:/out
        command: ["/bin/sh", "-c", "cp -a /home/factoryengine/out/. /out"]

    doxygen-ubuntu-resolute-amd64:
        build:
            context: .
            dockerfile: ./docker/doxygen.Dockerfile
            args:
                - BUILD_IMAGE=ubuntu:resolute
                - PLATFORM=linux/amd64
                - UID=1000
                - GID=1000
                - TZ=America/Toronto
                - PYTHON_VERSION=3.12.13
                - GCC_VERSION=16.1.0
                - GDB_VERSION=17.1
                - VALGRIND_VERSION=3.27.0
                - DOXYGEN_VERSION=1.17.0
                - CMAKE_VERSION=3.31.12
                - LLVM_VERSION=22
        platform: linux/amd64
        volumes:
            - ./out:/out
        command: ["/bin/sh", "-c", "cp -a /home/factoryengine/out/. /out"]

    doxygen-ubuntu-resolute-arm64:
        build:
            context: .
            dockerfile: ./docker/doxygen.Dockerfile
            args:
                - BUILD_IMAGE=ubuntu:resolute
                - PLATFORM=linux/arm64
                - UID=1000
                - GID=1000
                - TZ=America/Toronto
                - PYTHON_VERSION=3.12.13
                - GCC_VERSION=16.1.0
                - GDB_VERSION=17.1
                - VALGRIND_VERSION=3.27.0
                - DOXYGEN_VERSION=1.17.0
                - CMAKE_VERSION=3.31.12
                - LLVM_VERSION=22
        platform: linux/arm64
        volumes:
            - ./out:/out
        command: ["/bin/sh", "-c", "cp -a /home/factoryengine/out/. /out"]

    doxygen-debian-bullseye-amd64:
        build:
            context: .
            dockerfile: ./docker/doxygen.Dockerfile
            args:
                - BUILD_IMAGE=debian:bullseye
                - PLATFORM=linux/amd64
                - UID=1000
                - GID=1000
                - TZ=America/Toronto
                - PYTHON_VERSION=3.12.13
                - GCC_VERSION=16.1.0
                - GDB_VERSION=17.1
                - VALGRIND_VERSION=3.27.0
                - DOXYGEN_VERSION=1.17.0
                - CMAKE_VERSION=3.31.12
                - LLVM_VERSION=22
        platform: linux/amd64
        volumes:
            - ./out:/out
        command: ["/bin/sh", "-c", "cp -a /home/factoryengine/out/. /out"]

    doxygen-debian-bullseye-arm64:
        build:
            context: .
            dockerfile: ./docker/doxygen.Dockerfile
            args:
                - BUILD_IMAGE=debian:bullseye
                - PLATFORM=linux/arm64
                - UID=1000
                - GID=1000
                - TZ=America/Toronto
                - PYTHON_VERSION=3.12.13
                - GCC_VERSION=16.1.0
                - GDB_VERSION=17.1
                - VALGRIND_VERSION=3.27.0
                - DOXYGEN_VERSION=1.17.0
                - CMAKE_VERSION=3.31.12
                - LLVM_VERSION=22
        platform: linux/arm64
        volumes:
            - ./out:/out
        command: ["/bin/sh", "-c", "cp -a /home/factoryengine/out/. /out"]

    doxygen-debian-bookworm-amd64:
        build:
            context: .
            dockerfile: ./docker/doxygen.Dockerfile
            args:
                - BUILD_IMAGE=debian:bookworm
                - PLATFORM=linux/amd64
                - UID=1000
                - GID=1000
                - TZ=America/Toronto
                - PYTHON_VERSION=3.12.13
                - GCC_VERSION=16.1.0
                - GDB_VERSION=17.1
                - VALGRIND_VERSION=3.27.0
                - DOXYGEN_VERSION=1.17.0
                - CMAKE_VERSION=3.31.12
                - LLVM_VERSION=22
        platform: linux/amd64
        volumes:
            - ./out:/out
        command: ["/bin/sh", "-c", "cp -a /home/factoryengine/out/. /out"]

    doxygen-debian-bookworm-arm64:
        build:
            context: .
            dockerfile: ./docker/doxygen.Dockerfile
            args:
                - BUILD_IMAGE=debian:bookworm
                - PLATFORM=linux/arm64
                - UID=1000
                - GID=1000
                - TZ=America/Toronto
                - PYTHON_VERSION=3.12.13
                - GCC_VERSION=16.1.0
                - GDB_VERSION=17.1
                - VALGRIND_VERSION=3.27.0
                - DOXYGEN_VERSION=1.17.0
                - CMAKE_VERSION=3.31.12
                - LLVM_VERSION=22
        platform: linux/arm64
        volumes:
            - ./out:/out
        command: ["/bin/sh", "-c", "cp -a /home/factoryengine/out/. /out"]

    doxygen-debian-trixie-amd64:
        build:
            context: .
            dockerfile: ./docker/doxygen.Dockerfile
            args:
                - BUILD_IMAGE=debian:trixie
                - PLATFORM=linux/amd64
                - UID=1000
                - GID=1000
                - TZ=America/Toronto
                - PYTHON_VERSION=3.12.13
                - GCC_VERSION=16.1.0
                - GDB_VERSION=17.1
                - VALGRIND_VERSION=3.27.0
                - DOXYGEN_VERSION=1.17.0
                - CMAKE_VERSION=3.31.12
                - LLVM_VERSION=22
        platform: linux/amd64
        volumes:
            - ./out:/out
        command: ["/bin/sh", "-c", "cp -a /home/factoryengine/out/. /out"]

    doxygen-debian-trixie-arm64:
        build:
            context: .
            dockerfile: ./docker/doxygen.Dockerfile
            args:
                - BUILD_IMAGE=debian:trixie
                - PLATFORM=linux/arm64
                - UID=1000
                - GID=1000
                - TZ=America/Toronto
                - PYTHON_VERSION=3.12.13
                - GCC_VERSION=16.1.0
                - GDB_VERSION=17.1
                - VALGRIND_VERSION=3.27.0
                - DOXYGEN_VERSION=1.17.0
                - CMAKE_VERSION=3.31.12
                - LLVM_VERSION=22
        platform: linux/arm64
        volumes:
            - ./out:/out
        command: ["/bin/sh", "-c", "cp -a /home/factoryengine/out/. /out"]
